### ISSUE TITLE
Index 0 is out of bounds

### ISSUE THREAD

**Issue by AlexandreOndet** [dhsdshdhk/stegpy#6]
Traceback (most recent call last):
  File "/usr/local/bin/stegpy", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/stegpy/steg.py", line 52, in main
    host.read_message(password)
  File "/usr/local/lib/python3.8/dist-packages/stegpy/lsb.py", line 45, in read_message
    msg = decode_message(self.data)
  File "/usr/local/lib/python3.8/dist-packages/stegpy/lsb.py", line 167, in decode_message
    bits = 2 ** ((host_data[0] & 48) >> 4) # bits = 2 ^ (5th and 6th bits)    
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by dhsdshdhk** [comment]
I haven't looked at this program in a long time. Can you give provide the host file you tried to use or some context like how often this problem happens?

**Comment by izcoser** [comment]
I reproduced this class of failure on current `master` with a WAV host that has no mutable payload bytes: `decode_message()` indexed `host_data[0]` before checking for an empty carrier buffer.

Fixed in `5d3add5` by making `decode_message()` return an empty decoded buffer for empty carrier data, so `read_message()` now reaches the normal “No encoded info found” path instead of raising `IndexError`. Added regression coverage in `tests/test_lsb.py` and `tests/test_hosts.py`; full suite is passing (`36 passed`).

Closing as fixed.
